// starred
export const SET_STARRED_LIST = 'SET_STARRED_LIST'
export const SET_ACTIVE_REPOSITORY = 'SET_ACTIVE_REPOSITORY'
export const IS_LOADING_STARRED_LIST = 'IS_LOADING_STARRED_LIST'

// searchForm
export const SET_USERNAME_FIELD_VALUE = 'SET_USERNAME_FIELD_VALUE'

// repository
export const SET_REPOSITORY_README = 'SET_REPOSITORY_README'
export const IS_LOADING_README = 'IS_LOADING_README'

// githubUser
export const SET_GITHUB_USER_OBJECT = 'SET_GITHUB_USER_OBJECT'
export const IS_LOADING_GITHUB_USER_OBJECT = 'IS_LOADING_GITHUB_USER_OBJECT'
